### ISSUE TITLE
xram location

### ISSUE THREAD

**Issue by btashton** [sipeed/M1s_BL808_SDK#2]
Why is the xram located at the start of the ocram instead of using the dedicated xram

From the included linker scripts:
```
        xram_memory (!rx) : ORIGIN = 0x22020000, LENGTH = 16K 
```

From the datasheet?
```
XRAM(EMI)     | 0x40000000            | 16KB  | Shared RAM mainly for data communication among M0/LP/D0                                                   ```

**Comment by taorye** [comment]
It comes from Bouffalolab. They may just use ocram that with cache disabled to exchange data. Also memory started from [0x40000000 can of course be used due this link script](https://github.com/bouffalolab/bl_mcu_sdk/blob/master/bsp/board/bl808dk/bl808_flash_d0.ld).
