### ISSUE TITLE
E907 Firmware hangs initializing the SD card

### ISSUE THREAD

**Issue by stschake** [sipeed/M1s_BL808_SDK#3]
Hey,

since commit https://github.com/sipeed/M1s_BL808_example/commit/28e076758cec2bb2929c0fee5d1766aafb000392 the E907 firmware tries to initialize the SD card on start. Unfortunately, this hangs forever on my M1s Dock (with screen & camera populated), both with and without a SD card. The SD card works with a different card reader.

Note that it hangs forever since the function SDH_SendCardCommand has a timeout mechanism but SDH_GET_TIME has been #defined to be 0, so it's not effective. However that doesn't explain why it won't work with a SD card inserted.

Thanks,
Stefan

**Comment by taorye** [comment]
Hi,

You're right.

I have only a finite number of boards and they all work well so I had not encountered this problem.

But there was some feedback so I must take it seriously.

I have just disabled the initialization of the SD card for sidestepping the problem with this commit [sipeed/M1s_BL808_SDK@0be672](https://github.com/sipeed/M1s_BL808_SDK/commit/0be6722d5b9e8222bb79628393205b040198cdf8).

I will fix it in the future and then revert it to make SD card works again.
