### ISSUE TITLE
m1s_xram_wifi_upload_stream() in camera_streaming_through_wifi seems not working properly

### ISSUE THREAD

**Issue by hucuyuu** [sipeed/M1s_BL808_SDK#4]
I noticed that IP address was fiexed here. It seems to be a bug. 

https://github.com/sipeed/M1s_BL808_SDK/blob/a91c655dd83bb4b590faa079e00b9d89ab43b048/components/sipeed/e907/m1s_e907_xram/src/m1s_e907_xram_wifi.c#L218-L220

**Comment by kaidegit** [comment]
用private.ip和private.port代替试试？

**Comment by hucuyuu** [comment]
> 用private.ip和private.port代替试试？

好的工作，爱来自中国，感谢群里的哥们
